name: TrashPlugin
version: 1.0.0
main: com.yei_bai.trashplugin.TrashPlugin
api-version: '1.21'
folia-supported: true
author: yei_bai
description: 高级垃圾桶插件，支持个人垃圾桶、公共垃圾桶、扫地功能和物品回购

softdepend: [Vault]

permissions:
  trashplugin.use:
    description: 允许使用个人垃圾桶
    default: true
  trashplugin.public:
    description: 允许使用公共垃圾桶
    default: true
  trashplugin.admin:
    description: 管理员权限
    default: op

commands:
  trash:
    description: 打开个人垃圾桶
    usage: /trash
    aliases: [垃圾桶, 个人垃圾桶]
  publictrash:
    description: 打开公共垃圾桶
    usage: /publictrash [页面]
    aliases: [公共垃圾桶, 公共垃圾]
  trashadmin:
    description: 插件管理命令
    usage: /trashadmin <help|reload|setprice|sweeper|clear|econ>
    aliases: [垃圾桶管理, 垃圾管理]